sudo: false

language: php

php:
    - 7.2
    - 7.1

install:
  - composer install
  - composer global require chh/bob:^1@alpha
  - export PATH=$PATH:$HOME/.composer/vendor/bin/
  - bob install_dev_tools

script:
  - bob
